### ISSUE TITLE
APIに必要なAPI GatewayとLambdaの構築

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-terraform#28]
# Doneの定義
- APIの配信に必要なAPI GatewayとLamndaのリソースが構築されていること

# 補足情報
API：https://github.com/nekochans/lgtm-cat-api
参考：https://future-architect.github.io/articles/20200927/

**Comment by kobayashi-m42** [comment]
@keitakn すでに対応済みだけれど、ポイントは5か8くらいかな？

**Comment by keitakn** [comment]
@kobayashi-m42 PRの内容見た感じ結構作業量多そうだったから8で良さそう🐱！
