### ISSUE TITLE
lgtm-cat-api Lambdaの実行ロールにS3への権限を追加

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-terraform#30]
# Doneの定義
- lgtm-cat-api Lambdaの実行ロールにS3へファイルをアップロードするために必要な権限が追加されていること

# 補足情報
現状では権限が不足しているため、Lambda関数の処理でS3にファイルをアップロードするとエラーになってしまう。

**Comment by kobayashi-m42** [comment]
@keitakn 1ポイントくらいかな？🐱

**Comment by keitakn** [comment]
@kobayashi-m42 issue追加ありがとう！うん、1で大丈夫そう🐱！
