### ISSUE TITLE
本番用にlgtm-cat-lambdaのデプロイに必要なリソースの構築を行う

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-terraform#58]
# Doneの定義
- 本番用の Lambda のセキュリティグループが作成されていること

**Comment by kobayashi-m42** [comment]
@keitakn セキュリティグループの作成だけだから、1ポイントでどうかな？🐱

**Comment by keitakn** [comment]
@kobayashi-m42 作成ありがとう！
1ポイントで問題ないと思う🐱👍
