### ISSUE TITLE
Google Search Consoleのドメイン確認用TXTレコードを追加

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-terraform#6]
# Doneの定義
- Route53のレコードにGoogle Search Consoleのドメイン確認用TXTレコードが追加されている事

# 補足情報
設定内容としては以下のような形。

https://mariana.tokyo/posts/22

Google Search Consoleの利用を開始したい為、リリース時に必須ではないが、早めに対応を行うと良さそう。

**Comment by keitakn** [comment]
@kobayashi-m42 やる事としてはRoute53のホストゾーンにドメイン確認用TXTレコードを追加するだけだから、ストーリーポイント2とかで行けると思う🐱！（tfstateの単位は増やす必要アリ！）

**Comment by kobayashi-m42** [comment]
@keitakn 2でOKかと！
