### ISSUE TITLE
API LambdaのタイムアウトをAPI Gatewayのタイムアウトより短くする

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/lgtm-cat-terraform#61]
# Doneの定義
- 表題の通り

# 補足情報
API Gatewayのタイムアウトは30秒。
https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/limits.html#:~:text=%E3%81%84%E3%81%84%E3%81%88-,%E6%9C%80%E5%A4%A7%E7%B5%B1%E5%90%88%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%A2%E3%82%A6%E3%83%88,-30%20%E7%A7%92

なお、LambdaのタイムアウトをAPI Gatewayyより短くしLambdaがタイムアウトになった場合、レスポンスは 500 { "message": "Internal Server Error" }になる。

**Comment by kobayashi-m42** [comment]
@keitakn タイムアウトを変更するだけだから1ポイントでどうかな？

**Comment by keitakn** [comment]
@kobayashi-m42 作成ありがとう🐱！
1ポイントで問題なさそう👌
