### ISSUE TITLE
CIの設定を追加

### ISSUE THREAD

**Issue by keitakn** [nekochans/lgtm-cat-terraform#7]
# Doneの定義
- PR作成時に `terraform fmt -recursive -check` が実行され、チェックを追加していない場合はマージ出来ないようになっている事

**Comment by keitakn** [comment]
@kobayashi-m42 これも事後で https://github.com/nekochans/lgtm-cat-terraform/pull/8 で対応済なんだけど、ストーリーポイント1で良いと思う🐱！

**Comment by kobayashi-m42** [comment]
@keitakn うん！1でOKだと思う！
